[greeter]
background = /usr/share/backgrounds/default-wallpaper.png
theme-name = Arc-Dark
icon-theme-name = Papirus-Dark
font-name = Sans 11
position = 50%,center 50%,center
default-user-image = /usr/share/pixmaps/cyslogo.png
hide-user-image = false
screensaver-timeout = 60
