#!/bin/bash

lb config noauto \
    --architectures amd64 \
    --distribution bookworm \
    --archive-areas "main contrib non-free non-free-firmware" \
    --linux-flavours amd64 \
    --debian-installer false \
    --bootappend-live "boot=live components quiet splash" \
    --mode debian \
    --system live \
    --binary-images iso-hybrid \
    --apt-recommends true \
    --apt-indices false \
    --bootloaders grub-efi \
    --image-name security-distro \
    --iso-application "Security Linux Distro" \
    --iso-volume "SEC-LINUX" \
    "${@}"
