Window.SetBackgroundTopColor(0.05, 0.1, 0.2);
Window.SetBackgroundBottomColor(0.0, 0.05, 0.1);

logo.image = Image.Text("Cyscom Security OS", 1, 1, 1);
logo.sprite = Sprite(logo.image);
logo.sprite.SetX(Window.GetWidth() / 2 - logo.image.GetWidth() / 2);
logo.sprite.SetY(Window.GetHeight() / 2 - logo.image.GetHeight() / 2);

status = "Booting...";
status_image = Image.Text(status, 0.6, 0.8, 1);
status_sprite = Sprite(status_image);
status_sprite.SetX(Window.GetWidth() / 2 - status_image.GetWidth() / 2);
status_sprite.SetY(Window.GetHeight() / 2 + 100);
